using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CollisionDamage : MonoBehaviour
{
    [SerializeField]
    private int damage = 100;

    private void OnTriggerEnter2D(Collider2D collision)
    {
        IDamagable damagable = collision.GetComponent<IDamagable>();

        if (collision.GetComponent<Waypoint>() != null)
        {
            return;
        }

        if (damagable != null)
        {
            damagable.onDamage(damage);
            VisualUI.Get().onCollision();

        }
    }
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
